name: Deploy Webapp
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-react npm run test

